version: '3.6'
services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
    - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  graphql-engine:
    image: hasura/graphql-engine:v2.33.1-ce
    ports:
    - '8080:8080'
    depends_on:
    - postgres
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
      ## enable the console served by server
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true' # set to "false" to disable console
      ## enable debugging mode. It is recommended to disable this in production
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_ADMIN_SECRET: password
      ## Auth0 public key (see https://hasura.io/learn/ja/graphql/hasura/authentication/3-setup-env-vars-hasura/) 
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS512", "key": "-----BEGIN CERTIFICATE-----\nMIIDATCCAemgAwIBAgIJOXdbAkg04WXhMA0GCSqGSIb3DQEBCwUAMB4xHDAaBgNV\nBAMTE29wdGh1Yi51cy5hdXRoMC5jb20wHhcNMjAwNjIwMDMwNzE5WhcNMzQwMjI3\nMDMwNzE5WjAeMRwwGgYDVQQDExNvcHRodWIudXMuYXV0aDAuY29tMIIBIjANBgkq\nhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyntvI3QbiK+5R5S6k45OT4Y+qc1/jlt4\nljFkK979ZfBLenmWi/wMMG3+OIqxdHzFNg1FBHC0DQkLTG4mstV+SI7vozbinivw\n0SC9nHfH09HCEpuUxKohSWYX0rmAFpzqBDVqOO5SYvKBYVZ2oKJtTXh+qQen6Xm6\nSnn8Ea4jJEcJ4WecfCpZZVrr6CFfGVJRRvDQoNU2nzgWNPHp5hmXciVODvghC2NR\nrbS5En961AkmkhUW+w8vKtoKUKF+450Yod5hgwmhpS+yh6/Uxh3ADOii9lbKZbuf\nCc0fcngUxctPGll5obMTNIRIGjUOOkB0KQcsDxsm6BnIkFgfkbZg4wIDAQABo0Iw\nQDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBSW86fVY7bSNIkWSHL9nISrazSY\nAjAOBgNVHQ8BAf8EBAMCAoQwDQYJKoZIhvcNAQELBQADggEBAKgZWqyrmS3tU1Wy\nEXXzWRl28tgFVh8diT4HBl49ULm5bfN1JrHlX5swqfFGLu0Yd1IhJMT7K5gkL76J\nGQaNBz8VdB4XRsI7wio/cBH5IYekGZbMnzjhh5hMWG6hsJD8fj6SIX77JFFVzXfE\nzBu9IuPxhnctMmxp/ZEkF0bLkpQFImCZIXYgHLr6/mwim2TuOXeik0rpHMmrwZOY\nJhgq92ScGp5n+8AJN4VONiwcXvGBH2fFF+YwcRLWvlRfhs3HBJW8LN4Hwft1+reN\nIC1iaajsQk+6MSJE7nZPeliTsQnSJI/MuDsPPATYuLjrOeSGoyXaPIP9MK1af+tm\nG1l94eQ=\n-----END CERTIFICATE-----"}'
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: anonymous
volumes:
  db-data:

